#trigger:
#- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotnet_version_suffix: $(BuildID).$(SourceBranchName)

steps:
- script: dotnet build NWebsec-CI.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build NWebsec-CI.sln $(buildConfiguration)'
