#trigger:
#- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  sln: 'NWebsec-CI.sln'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    projects: '$(sln)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: $(sln)
    nobuild: true
    arguments: '--configuration $(buildConfiguration)'

- script: echo "##vso[task.setvariable variable=versionSuffix]--version-suffix $(Build.BuildID).$(Build.SourceBranchName)"
  condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'buildmaster'))
  displayName: 'Version suffix'

- script: dotnet pack $(sln) --configuration $(buildConfiguration) --no-build -o $(Build.ArtifactStagingDirectory) $(versionSuffix)
  displayName: 'Pack'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: nupkgs


    #condition: (succeeded(),in($(Build.SourceBranchName), 'master', 'dev'))